spring:
  application:
    name: invest-trader-bot-fiverr
  profiles:
    active: dev
paypal:
  client-id: AXN7e5ICc2oU9lVtGYJdIm2zkmtKZTCmMoStR6o9Y1VlzIpQiuHUzhVjOx3RPOgjhe19gabb9jxFsnLg
  client-secret: EMjGGESr5YVbHrKho9XPI7tHgRUdo0dVDEVg6sGSBn3GhuX7D_O4lTcFWQ3wjuqPiQ1hiM6UpSaWNcGB
  mode: sandbox # Use #sandbox' for testing and 'live' for Production
subscription:
  type:
    monthly: 25,00 €
    weekly: 10,00 €